### PR TITLE
Fix: hide assigned tasks if campaign in past on rider signup page.

### LINKED ISSUE #306: Don't show "N available" on campaign singup if campaign is in past
CleanShot 2024-03-29 at 21 10 08@2x

### PR DESCRIPTION
**Pull request by teesloane**
Fixes #306 . 

**Before/After:**

CleanShot 2024-04-10 at 14 33 25@2x

### CODE REVIEW

File: lib/bike_brigade_web/live/campaign_signup_live/index.ex [hunk 1]
```diff
@@ -122,13 +122,18 @@ defmodule BikeBrigadeWeb.CampaignSignupLive.Index do
...
-        case assigns.total_tasks - assigns.filled_tasks do
-          0 -> {"text-gray-600", "Fully Assigned"}
-          _ -> {"text-red-400", "#{assigns.total_tasks - assigns.filled_tasks} Available"}
-        end
+      cond do
+        assigns.filled_tasks == nil ->
+          {"text-gray-600", "N/A"}
+
+        campaign_in_past(assigns.campaign) ->
+          {"text-gray-600", "N/A"}
```
Comment (mveytsman) [inline lib/bike_brigade_web/live/campaign_signup_live/index.ex:130]: I think instead of "N/A" this should say "Complete" 

WDYT?

**Review by mveytsman — CHANGES_REQUESTED** [review]

File: lib/bike_brigade_web/live/campaign_signup_live/index.ex (hunk 1 above)
Comment (mveytsman) [reply lib/bike_brigade_web/live/campaign_signup_live/index.ex:130]: Or  "Campaign over" to match https://github.com/bikebrigade/dispatch/pull/314

**Review by mveytsman — APPROVED** [review]
LGTM!
