### PR TITLE
Fix: only show public programs in 48 hour CTA.

### LINKED ISSUE #338: Riders needed alert
The alert box is not mindful of hidden campaigns. This could create some confusion during the transition phase when not all campaigns are available in the portal.
image

### PR DESCRIPTION
**Pull request by teesloane**
Fixes #338.

### CODE REVIEW

File: lib/bike_brigade/delivery.ex [hunk 1]
```diff
@@ -259,9 +259,12 @@ defmodule BikeBrigade.Delivery do
       from c in Campaign,
         distinct: [asc: c.id],
         join: t in assoc(c, :tasks),
+        join: p in assoc(c, :program),
         where:
-          c.delivery_start <= ^forty_eight_hours_from_now and c.delivery_start >= ^now and
-            is_nil(t.assigned_rider_id),
+          c.delivery_start <= ^forty_eight_hours_from_now
+          and p.public == true
+          and c.delivery_start >= ^now
```
Comment (mveytsman) [inline lib/bike_brigade/delivery.ex:266]:
```suggestion
          c.delivery_start <= ^forty_eight_hours_from_now
          and c.delivery_start >= ^now
          and p.public == true
```

**Review by mveytsman — APPROVED** [review]
Super minor nit about ordering the constraints in the query otherwise :shipit:
