### PR TITLE
fix: remove date filter when fetching campaign_ids

### LINKED ISSUE #369: Riders Needed! section does not link to campaign sign-up across week boundaries
Bug from Jon his description below

**Describe the bug**

On Sunday May 19th, from the Home screen I saw the callout for  "Riders Needed! | 2 Unassigned deliveries | Through Ruff Times are looking for riders for the next 48 hours." When I clicked on the "Sign up for Deliveries" link, it redirected me to a page that said "No campaigns set up yet for the week of May 13." I expected to be redirected to a page that allowed me to sign up for Through Ruff Times' campaign on Tuesday May 21st. My understanding is that the "Riders Needed!" callout will show all the campaigns in the next 48 hours with unclaimed rides, but that it links to a page which groups campaigns by week and shows only the current week. Since the campaign date of Tuesday May 21st is in a different week than today, Sunday May 19th, nothing comes up.

**Steps to Reproduce**

I think the bug is sensitive to the day of the week. Ensure you are looking at the view on a Sunday with a scheduled Tuesday campaign that has unclaimed deliveries.
1. Open https://dispatch.bikebrigade.ca/home
2. Under the "Riders Needed!" callout, click on the Sign up for deliveries button

Image

### PR DESCRIPTION
**Pull request by teesloane**
fixes #369 

Here is a video demonstrating the bug on a sunday, as well as the fix:

https://github.com/bikebrigade/dispatch/assets/12987958/28951629-c34f-4149-b913-9aa3e59c1f49

## Describe your changes

- when list_campaigns is called with an option of `campaign_ids`, we disable filtering by start/end date.

@mveytsman any ideas on how I could write a test for this that simulates that it's a sunday locally and the campaigns in question are on a monday (without changing the system under test?)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added tests.
- [ ] Are there other PRs or Issues that I should link to here?
- [ ] Will this be part of a product update? If yes, please write one phrase
      about this update in the description above.

### CODE REVIEW

**Comment by teesloane** [comment]
Also, I added some needed padding on desktop.

image

(`1` is from before, `2` is after)

File: lib/bike_brigade/delivery.ex [hunk 1]
```diff
@@ -214,34 +214,32 @@ defmodule BikeBrigade.Delivery do
...
-          dynamic([campaign: c], ^filter and c.delivery_start <= ^date_time)
-
-        _ ->
-          filter
-      end
-
-    # sometimes we just want to fetch campaigns with specific ids
-    # (such as when we need to display campaigns that urgently need a rider)
-    filter =
+      # First we check if we are fetching with campaign_ids
```
Comment (mveytsman) [inline lib/bike_brigade/delivery.ex:217]: I love this but I feel we can refactor this into a `with`

Happy to pair on it!

**Review by mveytsman — APPROVED** [review]
Love how simple it is - i do want to refactor this into a `with` (happy to pair!)

**Review by mveytsman — CHANGES_REQUESTED** [review]
oops meant to not approve it 🐵

**Review by mveytsman — APPROVED** [review]

**Comment by mveytsman** [comment]
Did it work?

**Comment by teesloane** [comment]
> Did it work?

I forgot to test yesterday 🙃

**Comment by mveytsman** [comment]
@teesloane is this good to go?

**Comment by teesloane** [comment]
sorry, it's been a while and I forgot about this. I need to revisit the code to make sure I feel confident. I'll aim to merge it in on the weekend :)
